INSERT INTO movies (title, director, is_showing) VALUES
('Batman Returns','Tim Burton',False),
('Batman Forever','Joel Schumacher',False),
('Batman & Robin','Joel Schumacher',False),
('Steel','Kenneth Johnson',False),
('Catwoman','Pitof',False),
('Constantine','Francis Lawrence',False),
('Batman Begins','Christopher Nolan',False),
('Superman Returns','Bryan Singer',False),
('The Dark Knight','Christopher Nolan',False),
('Watchmen','Zack Snyder',False),
('Jonah Hex','Jimmy Hayward',False),
('Green Lantern','Martin Campbell',False),
('The Dark Knight Rises','Christopher Nolan',False),
('Man of Steel','Zack Snyder',False),
('Batman v Superman: Dawn of Justice','Zack Snyder',False),
('Suicide Squad','David Ayer',False),
('Wonder Woman','Patty Jenkins',False),
('Justice League','Zack Snyder/Joss Whedon',False),
('Aquaman','James Wan',False),
('Shazam!','David F. Sandberg',False),
('Joker','Todd Phillips',False),
('Birds of Prey','Cathy Yan',False),
('Wonder Woman 1984','Patty Jenkins',False),
('The Suicide Squad','James Gunn',False),
('The Batman','Matt Reeves',False),
('Black Adam','Jaume Collet-Serra',False),
('Shazam! Fury of the Gods','David F. Sandberg',False),
('The Flash','Andy Muschietti',False),
('Blue Beetle','Ángel Manuel Soto',False),
('Aquaman and the Lost Kingdom','James Wan',False),
('Blade','Stephen Norrington',False),
('X-Men','Bryan Singer',False),
('Blade II','Guillermo del Toro',False),
('Spider-Man','Sam Raimi',False),
('Daredevil','Mark Steven Johnson',False),
('Hulk','Ang Lee',False),
('X2: X-Men United','Bryan Singer',False),
('The Punisher','Jonathan Hensleigh',False),
('Spider-Man 2','Sam Raimi',False),
('Blade: Trinity','David S. Goyer',False),
('Elektra','Rob Bowman',False),
('Fantastic Four','Tim Story',False),
('X-Men: The Last Stand','Brett Ratner',False),
('Ghost Rider','Mark Steven Johnson',False),
('Spider-Man 3','Sam Raimi',False),
('Fantastic Four: Rise of the Silver Surfer','Tim Story',False),
('Iron Man','Jon Favreau',False),
('The Incredible Hulk','Louis Leterrier',False),
('Punisher: War Zone','Lexi Alexander',False),
('X-Men Origins: Wolverine','Gavin Hood',False),
('Iron Man 2','Jon Favreau',False),
('Thor','Kenneth Branagh',False),
('Captain America: The First Avenger','Joe Johnston',False),
('X-Men: First Class','Matthew Vaughn',False),
('Ghost Rider: Spirit of Vengeance','Neveldine/Taylor',False),
('The Avengers','Joss Whedon',False),
('The Amazing Spider-Man','Marc Webb',False),
('Iron Man 3','Shane Black',False),
('The Wolverine','James Mangold',False),
('Thor: The Dark World','Alan Taylor',False),
('Captain America: The Winter Soldier','Russo Brothers',False),
('The Amazing Spider-Man 2','Marc Webb',False),
('X-Men: Days of Future Past','Bryan Singer',False),
('Guardians of the Galaxy','James Gunn',False),
('Logan','James Mangold',False),
('Spider-Man: Homecoming','Jon Watts',False),
('Thor: Ragnarok','Taika Waititi',False),
('Black Panther','Ryan Coogler',False),
('Avengers: Infinity War','Russo Brothers',False),
('Ant-Man and the Wasp','Peyton Reed',False),
('Captain Marvel','Anna Boden & Ryan Fleck',False),
('Avengers: Endgame','Russo Brothers',False),
('Spider-Man: Far From Home','Jon Watts',False),
('The Bride!','Maggie Gyllenhaal',True),
('Hoppers','Daniel Chong',True),
('Nuremberg','James Vanderbilt',True);